from pathlib import Path

ROOT = Path('/home/ubuntu/crewup-work/landing-samples/data-driven-landing-template/sabri-five-format-samples')
ROOT.mkdir(parents=True, exist_ok=True)

FONT = """<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin><link href=\"https://fonts.googleapis.com/css2?family=Pretendard:wght@400;500;600;700;800;900&family=DM+Sans:wght@400;600;700;800;900&display=swap\" rel=\"stylesheet\">"""
BASE_CSS = r"""
*{box-sizing:border-box} html{scroll-behavior:smooth} body{margin:0;font-family:Pretendard,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:var(--ink);background:var(--bg);line-height:1.45} a{text-decoration:none;color:inherit} button{font-family:inherit} img{max-width:100%;display:block}.phone{width:min(100%,430px);margin:0 auto;background:var(--surface);min-height:100vh;position:relative;overflow:hidden}.wm{position:fixed;right:16px;bottom:84px;z-index:20;background:rgba(0,0,0,.55);color:white;font-size:10px;font-weight:900;letter-spacing:.16em;padding:7px 10px;border-radius:999px;backdrop-filter:blur(12px)}.cta-fixed{position:sticky;bottom:14px;width:calc(100% - 28px);margin:26px auto 0;z-index:30}.cta-fixed a,.cta-fixed button{width:100%;border:0;border-radius:999px;background:var(--cta);color:var(--ctaText);font-weight:900;font-size:16px;padding:17px 20px;box-shadow:0 16px 40px rgba(0,0,0,.22);display:flex;align-items:center;justify-content:center;gap:8px}.section{padding:26px 20px}.label{display:inline-flex;align-items:center;gap:6px;font-size:12px;font-weight:900;letter-spacing:.02em;color:var(--accent);text-transform:uppercase}.h1{font-size:34px;line-height:1.02;letter-spacing:-1.2px;margin:12px 0 12px;font-weight:950}.h2{font-size:24px;line-height:1.08;letter-spacing:-.7px;margin:8px 0 12px;font-weight:950}.lead{font-size:15px;color:var(--muted);margin:0}.pill{display:inline-flex;border-radius:999px;padding:8px 12px;font-weight:900;font-size:12px;background:var(--pill);color:var(--pillText)}.card{border-radius:24px;background:var(--card);box-shadow:var(--shadow);border:1px solid var(--line)}.grid{display:grid;gap:12px}.small{font-size:12px;color:var(--muted)}.price{font-family:'DM Sans',Pretendard,sans-serif;font-size:31px;font-weight:950;letter-spacing:-1px}.safe-bottom{height:96px}.toast{position:fixed;left:50%;bottom:82px;transform:translateX(-50%) translateY(20px);opacity:0;background:#111;color:white;border-radius:999px;padding:10px 14px;font-size:12px;font-weight:800;transition:.25s;z-index:50}.toast.show{opacity:1;transform:translateX(-50%) translateY(0)}
@media(min-width:760px){body{background:#f3f4f6}.phone{margin:28px auto;border-radius:34px;box-shadow:0 30px 80px rgba(0,0,0,.18);min-height:860px}.wm{right:calc(50% - 198px)}}
"""
JS = """<script>function ping(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg||'실제 상품에서는 카카오/예약 링크로 연결됩니다';document.body.appendChild(t);requestAnimationFrame(()=>t.classList.add('show'));setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),300)},1700)}document.querySelectorAll('[data-ping]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();ping(el.dataset.ping)}));</script>"""

def page(title, css_vars, css, body):
    return f"""<!doctype html><html lang=\"ko\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>{title}</title>{FONT}<style>:root{{{css_vars}}}{BASE_CSS}{css}</style></head><body><main class=\"phone\">{body}<div class=\"wm\">CREWUP SAMPLE</div><div class=\"safe-bottom\"></div></main>{JS}</body></html>"""

variants = []

# 1 Lookbook Gallery
css1 = """
.look-hero{padding:18px 16px 22px}.top{display:flex;align-items:center;justify-content:space-between;margin-bottom:18px}.brand{font-weight:950}.hero-photo{height:360px;border-radius:32px;background:url('https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=900&q=82') center/cover;position:relative;overflow:hidden}.hero-photo:after{content:'';position:absolute;inset:0;background:linear-gradient(to bottom,transparent 35%,rgba(0,0,0,.76))}.hero-copy{position:absolute;left:18px;right:18px;bottom:18px;color:white;z-index:1}.hero-copy .h1{font-size:38px;margin-bottom:8px}.chips{display:flex;gap:8px;overflow:auto;padding:6px 0 0}.chip{white-space:nowrap;padding:9px 12px;border-radius:999px;background:#fff;border:1px solid #f0d9df;font-weight:850;font-size:12px}.gallery{display:grid;grid-template-columns:1fr 1fr;gap:12px}.design{overflow:hidden}.design .pic{height:170px;background-size:cover;background-position:center}.design .txt{padding:13px}.design b{display:block;font-size:15px}.design span{font-size:12px;color:#7c6470}.design .ask{margin-top:10px;border-radius:999px;background:#191014;color:white;padding:9px 11px;text-align:center;font-size:11px;font-weight:900;display:inline-flex;white-space:nowrap;max-width:100%}.quote{padding:18px;background:#fff4f6;border-radius:26px;color:#3a2229}.quote b{display:block;margin-bottom:8px}.flow{display:grid;grid-template-columns:1fr 1fr;gap:10px}.flow div{padding:13px;border-radius:18px;background:white;border:1px solid #f3dce2;font-size:12px;font-weight:800}.cta-fixed a{background:#ff385c}
"""
body1 = """
<section class="look-hero"><div class="top"><div><div class="brand">온네일 성수</div><div class="small">성수역 4분 · 1:1 예약제</div></div><span class="pill">6월 신규 20명</span></div><div class="hero-photo"><div class="hero-copy"><span class="label">Lookbook</span><h1 class="h1">이번 달 아트와 가격을 한눈에</h1><p>사진을 고르면 예상 비용과 가능 여부를 먼저 안내해드려요.</p></div></div><div class="chips"><span class="chip">데일리</span><span class="chip">시럽</span><span class="chip">웨딩</span><span class="chip">포인트아트</span></div></section>
<section class="section"><span class="label">먼저 고르는 디자인</span><h2 class="h2">마음에 드는 사진을 캡처해서 보내주세요</h2><div class="gallery"><article class="card design"><div class="pic" style="background-image:url('https://images.unsplash.com/photo-1610992015732-2449b76344bc?auto=format&fit=crop&w=700&q=82')"></div><div class="txt"><b>시럽 누드톤</b><span>젤 기본 포함 · 79,000원~</span><a class="ask" href="#" data-ping="시럽 누드톤 문의 예시">이 디자인 문의</a></div></article><article class="card design"><div class="pic" style="background-image:url('https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=700&q=82')"></div><div class="txt"><b>포인트 플라워</b><span>아트 2개 포함 · 89,000원~</span><a class="ask" href="#" data-ping="포인트 플라워 문의 예시">이 디자인 문의</a></div></article><article class="card design"><div class="pic" style="background-image:url('https://images.unsplash.com/photo-1607779097040-26e80aa78e66?auto=format&fit=crop&w=700&q=82')"></div><div class="txt"><b>웨딩 글로우</b><span>상담 후 견적 · 109,000원~</span><a class="ask" href="#" data-ping="웨딩 글로우 문의 예시">이 디자인 문의</a></div></article><article class="card design"><div class="pic" style="background-image:url('https://images.unsplash.com/photo-1600422209745-19f5d1d4cdf5?auto=format&fit=crop&w=700&q=82')"></div><div class="txt"><b>짧은 손톱 케어</b><span>케어 중심 · 59,000원~</span><a class="ask" href="#" data-ping="짧은 손톱 케어 문의 예시">이 디자인 문의</a></div></article></div></section>
<section class="section"><div class="quote"><b>왜 가격이 먼저 보이나요?</b>인스타 피드만 보고는 추가금이 헷갈리기 때문에, 예약 전에 기본가·제거비·가능 디자인을 먼저 안내합니다.</div></section>
<section class="section"><span class="label">예약 순서</span><h2 class="h2">사진 1장만 보내면 다음 단계가 정리됩니다</h2><div class="flow"><div>1. 원하는 사진 캡처</div><div>2. 현재 손톱 사진 전송</div><div>3. 가능 여부/추가금 안내</div><div>4. 희망 날짜 2개로 확정</div></div></section>
<div class="cta-fixed"><a href="#" data-ping="카카오 문의 버튼 예시">마음에 드는 디자인 보내기</a></div>
"""
variants.append(('01-lookbook-gallery','룩북형 갤러리',page('룩북형 네일 모바일 안내페이지',"--bg:#fff8fa;--surface:#fff;--ink:#221116;--muted:#80616a;--accent:#ff385c;--cta:#ff385c;--ctaText:#fff;--pill:#ffe6ec;--pillText:#c70d3f;--card:#fff;--line:#f3d9e1;--shadow:0 12px 28px rgba(179,43,82,.12);",css1,body1)))

# 2 Poster Event
css2 = """
.poster{background:radial-gradient(circle at 18% 10%,#fff07a 0 18%,transparent 19%),linear-gradient(180deg,#111 0%,#29110b 64%,#ff6a00 100%);color:#fff;min-height:100vh}.poster .section{padding:24px 22px}.stamp{display:inline-flex;border:2px solid #fff;border-radius:999px;padding:8px 12px;font-weight:950;transform:rotate(-5deg)}.poster h1{font-size:54px;line-height:.88;letter-spacing:-2.4px;margin:24px 0 18px;font-weight:1000}.poster .sub{font-size:17px;color:#ffe7c9;font-weight:700}.deal{margin:24px 0;padding:20px;border:2px solid rgba(255,255,255,.28);border-radius:28px;background:rgba(255,255,255,.08);backdrop-filter:blur(12px)}.deal .price{font-size:46px;color:#ffe45e}.poster-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.poster-card{background:#fff;color:#1b0b07;border-radius:20px;padding:15px;font-weight:900;min-height:92px}.poster-card span{display:block;font-size:12px;color:#8e4124;margin-bottom:8px}.count{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.count b{display:block;font-size:28px}.count div{text-align:center;background:#fff;color:#111;border-radius:18px;padding:12px 6px}.fine{color:#ffd7b5;font-size:12px}.cta-fixed a{background:#fff;color:#111}
"""
body2 = """
<div class="poster"><section class="section"><div style="display:flex;justify-content:space-between;align-items:center"><b>청소하는 날</b><span class="stamp">이번 주 6팀</span></div><h1>입주청소<br>견적 먼저<br>보여드립니다</h1><p class="sub">평수와 오염 사진만 보내면 기본 범위·추가 비용 가능성·가능 날짜를 먼저 정리해드립니다.</p><div class="deal"><span class="label" style="color:#ffe45e">Launch Offer</span><div class="price">평당 11,000원~</div><p class="fine">창틀 기본 점검 + 주방 후드 상태 확인 + 청소 전 체크리스트 포함</p></div></section><section class="section"><div class="poster-grid"><div class="poster-card"><span>문제 01</span>업체마다 포함 범위가 다름</div><div class="poster-card"><span>문제 02</span>곰팡이·후드 추가금 불안</div><div class="poster-card"><span>해결</span>사진 기반 사전 범위 안내</div><div class="poster-card"><span>보장</span>현장 추가는 동의 후 진행</div></div></section><section class="section"><h2 class="h2" style="color:white">마감 전 확인할 것</h2><div class="count"><div><b>6</b><span>남은 팀</span></div><div><b>3</b><span>필요 사진</span></div><div><b>10분</b><span>견적 정리</span></div></div><p class="fine" style="margin-top:16px">이사 날짜가 가까울수록 오전 시간대부터 마감됩니다.</p></section></div><div class="cta-fixed"><a href="#" data-ping="입주청소 견적 문의 예시">평수/사진 보내고 견적 받기</a></div>
"""
variants.append(('02-limited-event-poster','이벤트 포스터형',page('입주청소 이벤트 포스터형',"--bg:#111;--surface:#111;--ink:#fff;--muted:#ffd7b5;--accent:#ffe45e;--cta:#fff;--ctaText:#111;--pill:#fff;--pillText:#111;--card:#fff;--line:rgba(255,255,255,.2);--shadow:none;",css2,body2)))

# 3 Instagram Profile
css3 = """
.profile{padding:22px 18px;background:linear-gradient(180deg,#faf7ff,#fff)}.avatar{width:82px;height:82px;border-radius:26px;background:url('https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=500&q=82') center/cover;box-shadow:0 12px 32px rgba(75,46,191,.18)}.profile-head{display:flex;gap:15px;align-items:center}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:18px}.metrics div{text-align:center;border-radius:18px;background:white;border:1px solid #eee7ff;padding:11px 4px}.metrics b{display:block;font-size:18px}.link-list{display:grid;gap:11px;margin-top:18px}.link{display:flex;justify-content:space-between;align-items:center;padding:16px;border-radius:20px;background:white;border:1px solid #eee7ff;box-shadow:0 10px 24px rgba(87,65,180,.07);font-weight:950}.link small{display:block;color:#786d91;font-weight:700;margin-top:3px}.mini-feed{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:16px}.mini-feed div{height:110px;border-radius:16px;background-size:cover;background-position:center}.schedule{display:grid;gap:8px}.slot{display:flex;justify-content:space-between;background:#f3efff;border-radius:16px;padding:12px 14px;font-weight:850}.cta-fixed a{background:#6b4eff}.section.alt{background:#f8f5ff}
"""
body3 = """
<section class="profile"><div class="profile-head"><div class="avatar"></div><div><b style="font-size:20px">핏베이스 PT</b><p class="lead">합정역 3분 · 초보자 1:1 체형 분석</p><span class="pill" style="margin-top:9px">첫 상담 무료 체크</span></div></div><div class="metrics"><div><b>4.9</b><span class="small">후기 평점</span></div><div><b>4주</b><span class="small">첫 루틴</span></div><div><b>8명</b><span class="small">주간 상담</span></div></div><div class="link-list"><a class="link" href="#price"><span>PT 가격표<small>4회/8회/12회 패키지</small></span><b>›</b></a><a class="link" href="#routine"><span>내 몸 첫 4주 루틴<small>목표·통증·운동경험별 안내</small></span><b>›</b></a><a class="link" href="#schedule"><span>이번 주 상담 가능 시간<small>저녁/주말 슬롯 확인</small></span><b>›</b></a><a class="link" href="#faq"><span>등록 전 FAQ<small>강요 없는 상담/준비물</small></span><b>›</b></a></div></section><section class="section"><span class="label">사진으로 보는 공간</span><h2 class="h2">처음 와도 헤매지 않게</h2><div class="mini-feed"><div style="background-image:url('https://images.unsplash.com/photo-1576678927484-cc907957088c?auto=format&fit=crop&w=500&q=82')"></div><div style="background-image:url('https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=500&q=82')"></div><div style="background-image:url('https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=500&q=82')"></div></div></section><section class="section alt" id="price"><span class="label">가격표</span><h2 class="h2">첫 4주 스타터 PT</h2><div class="card" style="padding:18px"><div class="price">4회 220,000원~</div><p class="lead">체형 분석 리포트, 홈트 보완 루틴, 식단 체크리스트 포함</p></div></section><section class="section" id="schedule"><span class="label">예약 가능</span><h2 class="h2">이번 주 상담 슬롯</h2><div class="schedule"><div class="slot"><span>수요일 19:30</span><b>가능</b></div><div class="slot"><span>금요일 18:00</span><b>마감 임박</b></div><div class="slot"><span>토요일 11:00</span><b>가능</b></div></div></section><div class="cta-fixed"><a href="#" data-ping="PT 상담 문의 예시">카카오로 상담 시간 확인</a></div>
"""
variants.append(('03-instagram-profile-hub','인스타 프로필 허브형',page('PT 인스타 프로필 허브형',"--bg:#faf7ff;--surface:#fff;--ink:#201733;--muted:#74698d;--accent:#6b4eff;--cta:#6b4eff;--ctaText:#fff;--pill:#efeaff;--pillText:#5a35df;--card:#fff;--line:#eee7ff;--shadow:0 12px 26px rgba(87,65,180,.1);",css3,body3)))

# 4 Reservation Calendar
css4 = """
.res-hero{padding:22px 18px;background:linear-gradient(180deg,#e9f7ef,#fff)}.nav{display:flex;justify-content:space-between;align-items:center}.calendar{margin-top:20px;background:white;border-radius:28px;padding:16px;border:1px solid #dcefe3;box-shadow:0 16px 34px rgba(19,122,79,.09)}.days{display:grid;grid-template-columns:repeat(7,1fr);gap:7px;margin-top:12px}.day{height:48px;border-radius:15px;background:#f3fbf6;display:flex;align-items:center;justify-content:center;font-weight:900;color:#749282}.day.on{background:#16a36c;color:white}.day.soon{background:#ffeeb8;color:#6d4f00}.service{display:grid;gap:10px}.svc{display:flex;gap:12px;padding:14px;border-radius:20px;background:white;border:1px solid #dcefe3}.svc b{display:block}.svc .num{width:36px;height:36px;border-radius:12px;background:#16a36c;color:white;display:flex;align-items:center;justify-content:center;font-weight:950;flex:none}.checklist li{margin:9px 0;padding:12px 13px;background:#f5fbf7;border-radius:16px;font-weight:800}.cta-fixed a{background:#16a36c}.bar{height:10px;background:#dff1e6;border-radius:999px;overflow:hidden}.bar span{display:block;height:100%;width:68%;background:#16a36c}
"""
body4 = """
<section class="res-hero"><div class="nav"><b>그린 홈케어</b><span class="pill">예약형</span></div><h1 class="h1">가능한 날짜부터 확인하고 예약하세요</h1><p class="lead">베란다 곰팡이·욕실 실리콘·에어컨 케어는 사진 확인 후 작업 가능 범위와 시간을 먼저 안내합니다.</p><div class="calendar"><b>6월 예약 현황</b><div class="days"><div class="day">10</div><div class="day soon">11</div><div class="day">12</div><div class="day on">13</div><div class="day">14</div><div class="day on">15</div><div class="day">16</div><div class="day">17</div><div class="day soon">18</div><div class="day on">19</div><div class="day">20</div><div class="day">21</div><div class="day on">22</div><div class="day">23</div></div><p class="small">초록: 예약 가능 · 노랑: 마감 임박</p></div></section><section class="section"><span class="label">서비스 선택</span><h2 class="h2">사진을 보내기 전에 작업 범위를 고르세요</h2><div class="service"><div class="svc"><div class="num">1</div><div><b>욕실 곰팡이 집중 케어</b><span class="small">1~2시간 · 70,000원부터</span></div></div><div class="svc"><div class="num">2</div><div><b>입주 전 부분 홈케어</b><span class="small">사진 확인 후 견적</span></div></div><div class="svc"><div class="num">3</div><div><b>에어컨 필터/외관 케어</b><span class="small">모델 확인 필요</span></div></div></div></section><section class="section"><span class="label">예약 전 확인</span><h2 class="h2">문의할 때 이 4가지만 보내주세요</h2><ul class="checklist"><li>작업할 공간 사진 2~3장</li><li>주소 구/동과 주차 가능 여부</li><li>희망 날짜 2개</li><li>반려동물/엘리베이터 유무</li></ul></section><section class="section"><span class="label">한정 안내</span><h2 class="h2">이번 주 오전 슬롯 68% 마감</h2><div class="bar"><span></span></div><p class="lead" style="margin-top:12px">예약 확정 전에는 결제를 요구하지 않고, 사진 기준 예상 비용을 먼저 안내합니다.</p></section><div class="cta-fixed"><a href="#" data-ping="예약 가능일 확인 예시">가능 날짜 확인하기</a></div>
"""
variants.append(('04-reservation-calendar','예약 캘린더형',page('홈케어 예약 캘린더형',"--bg:#f4fbf6;--surface:#fff;--ink:#102319;--muted:#63746a;--accent:#16a36c;--cta:#16a36c;--ctaText:#fff;--pill:#dff5e8;--pillText:#137a4f;--card:#fff;--line:#dcefe3;--shadow:0 14px 30px rgba(19,122,79,.1);",css4,body4)))

# 5 Case Study Before After
css5 = """
.case-hero{padding:0 0 22px;background:#0b0f14;color:white}.ba{display:grid;grid-template-columns:1fr 1fr;height:330px}.ba div{background-size:cover;background-position:center;position:relative}.ba span{position:absolute;left:12px;top:12px;background:rgba(0,0,0,.72);color:white;border-radius:999px;padding:7px 10px;font-weight:950;font-size:12px}.case-copy{padding:22px}.case-copy .h1{color:white;font-size:31px;line-height:1.08;letter-spacing:-1px}.case-copy .lead{color:#cbd5e1}.timeline{position:relative;padding-left:20px}.timeline:before{content:'';position:absolute;left:5px;top:6px;bottom:6px;width:2px;background:#d9e7ff}.step{position:relative;margin-bottom:16px;background:white;border:1px solid #e3ebf7;border-radius:22px;padding:15px}.step:before{content:'';position:absolute;left:-20px;top:20px;width:12px;height:12px;border-radius:50%;background:#0866ff}.result{display:grid;grid-template-columns:1fr 1fr;gap:10px}.result div{border-radius:20px;background:#eef5ff;padding:15px}.result b{display:block;font-size:24px;color:#0866ff}.review{padding:18px;border-radius:26px;background:#0b0f14;color:white}.cta-fixed a{background:#0866ff}.tagrow{display:flex;gap:8px;flex-wrap:wrap}.tagrow span{background:#eff6ff;color:#0b55d9;border-radius:999px;padding:8px 10px;font-size:12px;font-weight:900}
"""
body5 = """
<section class="case-hero"><div class="ba"><div style="background-image:url('https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=600&q=82')"><span>Before</span></div><div style="background-image:url('https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=600&q=82')"><span>After</span></div></div><div class="case-copy"><span class="label" style="color:#8ec5ff">Case Study</span><h1 class="h1">입주 전 주방 후드와 창틀 오염을 4시간 안에 정리한 사례</h1><p class="lead">사진으로 오염도를 먼저 확인하고 기본 범위/추가 가능성을 사전 안내한 뒤 진행했습니다.</p></div></section><section class="section"><span class="label">상황</span><h2 class="h2">고객이 문의 전 걱정한 것</h2><div class="tagrow"><span>후드 기름때</span><span>창틀 먼지</span><span>추가금 걱정</span><span>이사 전날 일정</span></div></section><section class="section"><span class="label">진행 과정</span><h2 class="h2">작업은 이렇게 진행됐습니다</h2><div class="timeline"><div class="step"><b>1. 사진 5장 확인</b><p class="lead">주방, 욕실, 창틀, 바닥 상태를 먼저 확인했습니다.</p></div><div class="step"><b>2. 기본/추가 범위 분리</b><p class="lead">후드 내부 깊은 분해는 추가 확인 대상으로 분리했습니다.</p></div><div class="step"><b>3. 작업 후 사진 공유</b><p class="lead">완료 후 같은 구도 사진을 전달해 확인 시간을 줄였습니다.</p></div></div></section><section class="section"><span class="label">결과</span><h2 class="h2">숫자로 보는 결과</h2><div class="result"><div><b>4h</b><span>작업 시간</span></div><div><b>0원</b><span>사전 미고지 추가금</span></div><div><b>12장</b><span>완료 사진</span></div><div><b>4.9</b><span>후기 평점</span></div></div></section><section class="section"><div class="review">“이사 전날이라 급했는데 사진으로 범위를 먼저 알려줘서 안심됐어요. 작업 후 사진까지 받아서 바로 확인했습니다.”</div></section><div class="cta-fixed"><a href="#" data-ping="비슷한 사례 견적 문의 예시">우리 집도 비슷한지 문의하기</a></div>
"""
variants.append(('05-before-after-case','비포애프터 사례형',page('입주청소 비포애프터 사례형',"--bg:#f6f9ff;--surface:#fff;--ink:#0b1220;--muted:#66758a;--accent:#0866ff;--cta:#0866ff;--ctaText:#fff;--pill:#e7f0ff;--pillText:#0b55d9;--card:#fff;--line:#e3ebf7;--shadow:0 14px 30px rgba(8,102,255,.1);",css5,body5)))

for slug, name, html in variants:
    d = ROOT / slug
    d.mkdir(parents=True, exist_ok=True)
    (d / 'index.html').write_text(html, encoding='utf-8')
    (d / 'README.md').write_text(f"""# {name}\n\n## Design stance\n색상만 다른 템플릿이 아니라, 고객의 전환 질문 자체가 다른 독립 모바일 랜딩페이지 샘플입니다.\n\n## Best for\n- {name}\n- 소상공인 모바일 안내페이지 양식 마켓 검증\n\n## Core action\n고객이 카카오/전화/예약 링크로 문의하게 만드는 것.\n""", encoding='utf-8')

links = '\n'.join([f'<a class="item" href="{slug}/index.html"><b>{i+1}. {name}</b><span>{slug}</span></a>' for i,(slug,name,_) in enumerate(variants)])
index = f"""<!doctype html><html lang=\"ko\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>사비 원칙 5가지 모바일 랜딩 양식 샘플</title>{FONT}<style>*{{box-sizing:border-box}}body{{margin:0;font-family:Pretendard,-apple-system,sans-serif;background:#111;color:white}}main{{max-width:980px;margin:0 auto;padding:50px 20px}}h1{{font-size:48px;line-height:1;letter-spacing:-2px;margin:0 0 14px}}p{{color:#b7bdc9;font-size:17px}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px;margin-top:28px}}.item{{display:block;background:#1d2430;border:1px solid #303949;border-radius:24px;padding:20px;color:white;text-decoration:none;transition:.2s}}.item:hover{{transform:translateY(-3px);background:#263142}}.item b{{display:block;font-size:18px}}.item span{{display:block;color:#9aa5b8;margin-top:8px;font-size:13px}}</style></head><body><main><h1>사비 원칙 기반<br>5가지 모바일 랜딩 양식</h1><p>같은 색상 변형이 아니라 룩북, 포스터, 프로필 허브, 예약 캘린더, 비포애프터 사례형으로 정보 구조를 완전히 다르게 만든 테스트 샘플입니다.</p><div class=\"grid\">{links}</div></main></body></html>"""
(ROOT / 'index.html').write_text(index, encoding='utf-8')
(ROOT / 'README.md').write_text("""# 사비 원칙 기반 5가지 모바일 랜딩 양식 샘플\n\n## 목적\n결과물을 보고 이 작업이 가치 있는지 판단하기 위한 고객-facing 샘플 팩.\n\n## 샘플\n1. 룩북형 갤러리 — 이미지 선택/디자인 문의 중심\n2. 이벤트 포스터형 — 혜택/가격/마감 중심\n3. 인스타 프로필 허브형 — 링크인바이오/빠른 탐색 중심\n4. 예약 캘린더형 — 가능한 날짜/예약 전 정보 중심\n5. 비포애프터 사례형 — 문제/과정/결과/후기 중심\n\n## 판단 포인트\n색상만 다른 템플릿이 아니라, 업종과 목적에 따라 섹션 순서·정보 구조·CTA 방식이 달라질 수 있는지를 확인한다.\n""", encoding='utf-8')
print(ROOT)
for slug, name, _ in variants:
    print(ROOT / slug / 'index.html')
